// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function ListRemotes() {
  return window['go']['main']['App']['ListRemotes']();
}

export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function RpcCall(arg1, arg2) {
  return window['go']['main']['App']['RpcCall'](arg1, arg2);
}

export function SaveScheduledTask(arg1) {
  return window['go']['main']['App']['SaveScheduledTask'](arg1);
}
