// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRemotes() {
  return window['go']['main']['App']['ListRemotes']();
}

export function RpcCall(arg1, arg2) {
  return window['go']['main']['App']['RpcCall'](arg1, arg2);
}
