// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteScheduledTask(arg1:number):Promise<void>;

export function ListRemotes():Promise<Array<string>>;

export function ListScheduledTasks():Promise<Array<main.ScheduledTask>>;

export function RpcCall(arg1:string,arg2:string):Promise<string>;

export function SaveScheduledTask(arg1:main.ScheduledTask):Promise<number>;
